#!/usr/bin/env bash
# display information about subdomains

get_ip () {
	ans=$(dig "$2"."$1" | grep -A1 'ANSWER SECTION' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
	echo "$2" "$ans" | awk '{print "The subdomain "$1" is a "$2" record and points to "$3}'
}



if [ "$#" -eq 1 ]
then
	get_ip "$1" "www"
	get_ip "$1" "lb-01"
	get_ip "$1" "web-01"
	get_ip "$1" "web-02"
elif [ "$#" -eq 2 ]
then
	get_ip "$1" "$2"
fi
