#!/usr/bin/env bash
# Configures a new ubuntu machine to install and run nginx
# listening on port 80
# return "Hello World!" 

sudo apt update
sudo apt install -y nginx

sudo service nginx start

echo "Hello World!" > /var/www/html/index.html

printf %s "server {
	listen	80 default_server;
	listen	[::]:80 default_server;
	root	/var/www/html;
	index	index.html;
}" | sudo tee /etc/nginx/site-available/default

sudo service nginx restart
