#!/usr/bin/env bash
# Configures a new ubuntu machine to install and run nginx
# listening on port 80
# return "Hello World!" 

sudo apt update
sudo apt install -y nginx

sudo service nginx start


echo "<!DOCTYPE html>
<html>
<head>
    <title>Hello World!</title>
</head>
<body>
    <h1>Hello World!</h1>
</body>
</html>" | sudo tee /var/www/html/index.html

sudo service nginx reload
