#!/usr/bin/env bash
# Configre nginx to redirect 

sudo apt update
sudo apt install -y nginx

sudo service nginx start


echo "Hello World!" > /var/www/html/index.html

printf %s "server {
	listen	80 default_server;
	listen	[::]:80 default_server;
	root	/var/www/html;
	index	index.html;

	location /redirect_me {
	return 301 http://googl.com;
	}
}" > /etc/nginx/sites-available/default

sudo service nginx restart
