#!/usr/bin/env bash
# Configre nginx to redirect 

sudo apt update
sudo apt install -y nginx

sudo service nginx start

mkdir /etc/nginx/html
echo "Hello World!" > /etc/nginx/html/index.html

printf %s "server {
	listen	80 default_server;
	listen	[::]:80 default_server;
	root	/etc/nginx/html;
	index	index.html index.htm;

	location /redirect_me {
	return 301 http://googl.com/;
	}
}" > /etc/nginx/site_available/default

sudo service nginx restart
