#!/usr/bin/env bash
# Configre nginx to have a custom 404 page

sudo apt update
sudo apt install -y nginx

sudo service nginx start

echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

printf %s "server {
	listen	80 default_server;
	listen	[::]:80 default_server;
	root	/var/www/html;
	index	index.html;

	location /redirect_me {
	return 301 http://googl.com;
	}
	error_page 404 /404.html;
	location /404 {
	root /var/www/html;
	internal;
	}
}" > /etc/nginx/sites-available/default

sudo service nginx restart
