#!/usr/bin/env bash
# install and configure an HAproxy server

sudo apt update
sudo apt install -y haproxy

echo "ENABLED=1" > /etx/default/haproxy
sudo systemctl enable haproxy

printf %s "
frontend http
    bind *:80
    default_backend http_back

backend http_back
    balance roundrobin
    server 512451-web-01 34.203.29.40:80 check
    server 512451-web-02 54.164.120.187:80 check
" > /etc/haproxy/haproxy.cfg

sudo service haproxy restart
