#!/usr/bin/env bash
#a procces that's not easily killed
function wont_stop
{
	echo "I hate the kill command"
}
function _sigint_
{
	echo "Y U no love me?!"
}
function _terminate_
{
	rm -f "/var/run/myscript.pid"
	exit 1
}
echo "$$" > "/var/run/myscript.pid"
trap _terminate_ SIGQUIT
trap 'echo "I hate the kill command"; rm /var/run/holbertonscript.pid; exit 0;' SIGTERM
trap _sigint_ SIGINT
for ((;;));
do
	echo "To infinity and beyond"
done
