#!/usr/bin/env bash
#The FizzBuzz challange
a=1
while [ $a -le 100 ];
do
	if ((  a % 5 == 0  &&  a % 3 == 0 ));
	then
		echo "FizzBuzz"
	elif (( a % 5 == 0 ));
	then
		echo "Buzz"
	elif (( a % 3 == 0 ));
	then
		echo "Fizz"
	else
		echo $a
	fi
	((a++))
done
