#!/usr/bin/env bash
# fix the container to run nginx as the nginx user
sudo useradd -r nginx;
sed -i 's/80/8080/g' /etc/nginx/sites-available/default
sudo service nginx stop
echo 'user nginx;'>> /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
